### ISSUE TITLE
Vylepšení 

### ISSUE THREAD

**Issue by azidb** [jose1711/plugin.video.topserialy.sk#1]
Ahoj, chtělo by to přidat možnost výběru zdroje jelikož hromada videi nejde... Jinak super práce co odvádíš jen tak dál

**Comment by jose1711** [comment]
dik, mam za to, ze sa parsuju vsetky (podporovane) zdroje. je tiez mozne, ze mnohym videam "pomoze" manualna oprava openload vid https://github.com/kodi-czsk/script.module.stream.resolver/pull/30
