### ISSUE TITLE
chyba Video je na serveru, který není podporován

### ISSUE THREAD

**Issue by petrm74** [jose1711/plugin.video.topserialy.sk#2]
Zdravím,
mohl bych poprosit o aktualizaci doplňku? Zřejmě došlo k nějaké úpravě na webu, a hází to uvedenou chybu.
Log přikládám, díky

20:40:35 T:3828  NOTICE: ["Initializing provider topserialy.sk with settings {'downloads': '', 'quality': '0'}"]
20:40:56 T:1824  NOTICE: Previous line repeats 1 times.
20:40:56 T:1824   ERROR: dll_fgets emulated function failed
20:41:05 T:1464  NOTICE: ["Initializing provider topserialy.sk with settings {'downloads': '', 'quality': '0'}"]
20:41:09 T:7944  NOTICE: Previous line repeats 1 times.
20:41:09 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653031&cp=746f7073657269616c792e736b&
20:41:09 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653031&cp=746f7073657269616c792e736b&
20:41:09 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653033&cp=746f7073657269616c792e736b&
20:41:09 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653033&cp=746f7073657269616c792e736b&
20:41:09 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653034&cp=746f7073657269616c792e736b&
20:41:09 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653034&cp=746f7073657269616c792e736b&
20:41:09 T:4644 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653032&cp=746f7073657269616c792e736b&
20:41:09 T:4644   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653032&cp=746f7073657269616c792e736b&
20:41:12 T:5472  NOTICE: ["Initializing provider topserialy.sk with settings {'downloads': '', 'quality': '0'}"]
20:41:13 T:5472  NOTICE: [u'Found resolvable b3BlbmxvYWRmdWNrZG1jYXRyb2xscw==/7Rh5vabaXGY/']
20:41:13 T:5472  NOTICE: [u'Found resolvable http://www.flashx.tv/embed-vz91eqv82ss2-720x405.html']
20:41:13 T:5472  NOTICE: [u'Found resolvable //www.zumail.cz/tracker/i8eAfjhE3eWo8ne/']
20:41:13 T:5472  NOTICE: [u'Resolving b3BlbmxvYWRmdWNrZG1jYXRyb2xscw==/7Rh5vabaXGY/']
20:41:13 T:5472  NOTICE: [u'No resolver found for b3BlbmxvYWRmdWNrZG1jYXRyb2xscw==/7Rh5vabaXGY/']
20:41:13 T:5472  NOTICE: [u'Resolving http://www.flashx.tv/embed-vz91eqv82ss2-720x405.html']
20:41:13 T:5472  NOTICE: ["Using resolver 'flashx'"]
20:41:14 T:5472  NOTICE: [u'There was an error resolving http://www.flashx.tv/embed-vz91eqv82ss2-720x405.html']
20:41:14 T:5472  NOTICE: [u'Resolving //www.zumail.cz/tracker/i8eAfjhE3eWo8ne/']
20:41:14 T:5472  NOTICE: [u'No resolver found for //www.zumail.cz/tracker/i8eAfjhE3eWo8ne/']
20:41:17 T:7096   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653031&cp=746f7073657269616c792e736b&]
20:41:20 T:5556 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653031&cp=746f7073657269616c792e736b&
20:41:20 T:5556   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653031&cp=746f7073657269616c792e736b&
20:41:20 T:5556 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653034&cp=746f7073657269616c792e736b&
20:41:20 T:5556   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653034&cp=746f7073657269616c792e736b&
20:41:20 T:5556 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653033&cp=746f7073657269616c792e736b&
20:41:20 T:5556   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653033&cp=746f7073657269616c792e736b&
20:41:20 T:5556 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653032&cp=746f7073657269616c792e736b&
20:41:20 T:5556   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f61667465726d6174682d733031653032&cp=746f7073657269616c792e736b&
20:41:26 T:2944  NOTICE: ["Initializing provider topserialy.sk with settings {'downloads': '', 'quality': '0'}"]
20:41:30 T:7944  NOTICE: Previous line repeats 1 times.
20:41:30 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653031&cp=746f7073657269616c792e736b&
20:41:30 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653031&cp=746f7073657269616c792e736b&
20:41:30 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653032&cp=746f7073657269616c792e736b&
20:41:30 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653032&cp=746f7073657269616c792e736b&
20:41:30 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653033&cp=746f7073657269616c792e736b&
20:41:30 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653033&cp=746f7073657269616c792e736b&
20:41:30 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653034&cp=746f7073657269616c792e736b&
20:41:30 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653034&cp=746f7073657269616c792e736b&
20:41:30 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653035&cp=746f7073657269616c792e736b&
20:41:30 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653035&cp=746f7073657269616c792e736b&
20:41:30 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653037&cp=746f7073657269616c792e736b&
20:41:30 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653037&cp=746f7073657269616c792e736b&
20:41:30 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653038&cp=746f7073657269616c792e736b&
20:41:30 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653038&cp=746f7073657269616c792e736b&
20:41:30 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653039&cp=746f7073657269616c792e736b&
20:41:30 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653039&cp=746f7073657269616c792e736b&
20:41:30 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653130&cp=746f7073657269616c792e736b&
20:41:30 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653130&cp=746f7073657269616c792e736b&
20:41:30 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653036&cp=746f7073657269616c792e736b&
20:41:30 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653036&cp=746f7073657269616c792e736b&
20:41:31 T:6048  NOTICE: EMBY.kodimonitor -> Method: Playlist.OnClear Data: {"playlistid":1}
20:41:33 T:2128  NOTICE: ["Initializing provider topserialy.sk with settings {'downloads': '', 'quality': '0'}"]
20:41:33 T:2128  NOTICE: [u'Found resolvable b3BlbmxvYWRmdWNrZG1jYXRyb2xscw==/csSz53FSwdQ/']
20:41:33 T:2128  NOTICE: [u'Found resolvable http://www.flashx.tv/embed-u0qsgnzfd1vl-720x405.html']
20:41:33 T:2128  NOTICE: [u'Found resolvable //www.zumail.cz/tracker/i8eAfjhE3eWo8ne/']
20:41:33 T:2128  NOTICE: [u'Resolving b3BlbmxvYWRmdWNrZG1jYXRyb2xscw==/csSz53FSwdQ/']
20:41:34 T:2128  NOTICE: [u'No resolver found for b3BlbmxvYWRmdWNrZG1jYXRyb2xscw==/csSz53FSwdQ/']
20:41:34 T:2128  NOTICE: [u'Resolving http://www.flashx.tv/embed-u0qsgnzfd1vl-720x405.html']
20:41:34 T:2128  NOTICE: ["Using resolver 'flashx'"]
20:41:34 T:2128  NOTICE: [u'There was an error resolving http://www.flashx.tv/embed-u0qsgnzfd1vl-720x405.html']
20:41:34 T:2128  NOTICE: [u'Resolving //www.zumail.cz/tracker/i8eAfjhE3eWo8ne/']
20:41:34 T:2128  NOTICE: [u'No resolver found for //www.zumail.cz/tracker/i8eAfjhE3eWo8ne/']
20:41:37 T:7096   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653031&cp=746f7073657269616c792e736b&]
20:41:39 T:6048  NOTICE: EMBY.kodimonitor -> Method: Playlist.OnClear Data: {"playlistid":1}
20:41:41 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653031&cp=746f7073657269616c792e736b&
20:41:41 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653031&cp=746f7073657269616c792e736b&
20:41:41 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653130&cp=746f7073657269616c792e736b&
20:41:41 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653130&cp=746f7073657269616c792e736b&
20:41:41 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653039&cp=746f7073657269616c792e736b&
20:41:41 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653039&cp=746f7073657269616c792e736b&
20:41:41 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653038&cp=746f7073657269616c792e736b&
20:41:41 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653038&cp=746f7073657269616c792e736b&
20:41:41 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653037&cp=746f7073657269616c792e736b&
20:41:41 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653037&cp=746f7073657269616c792e736b&
20:41:41 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653036&cp=746f7073657269616c792e736b&
20:41:41 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653036&cp=746f7073657269616c792e736b&
20:41:41 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653035&cp=746f7073657269616c792e736b&
20:41:41 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653035&cp=746f7073657269616c792e736b&
20:41:41 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653034&cp=746f7073657269616c792e736b&
20:41:41 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653034&cp=746f7073657269616c792e736b&
20:41:41 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653033&cp=746f7073657269616c792e736b&
20:41:41 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653033&cp=746f7073657269616c792e736b&
20:41:41 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653032&cp=746f7073657269616c792e736b&
20:41:41 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f6167656e742d782d733031653032&cp=746f7073657269616c792e736b&
20:42:10 T:1824   ERROR: dll_fgets emulated function failed
20:42:24 T:4580   ERROR: Previous line repeats 1 times.
20:42:24 T:4580  NOTICE: ['SOSAC Loading subscriptions']
20:42:59 T:2520  NOTICE: ["Initializing provider topserialy.sk with settings {'downloads': '', 'quality': '0'}"]
20:43:03 T:7944  NOTICE: Previous line repeats 1 times.
20:43:03 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653031&cp=746f7073657269616c792e736b&
20:43:03 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653031&cp=746f7073657269616c792e736b&
20:43:03 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653032&cp=746f7073657269616c792e736b&
20:43:03 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653032&cp=746f7073657269616c792e736b&
20:43:03 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653033&cp=746f7073657269616c792e736b&
20:43:03 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653033&cp=746f7073657269616c792e736b&
20:43:03 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653034&cp=746f7073657269616c792e736b&
20:43:03 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653034&cp=746f7073657269616c792e736b&
20:43:03 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653035&cp=746f7073657269616c792e736b&
20:43:03 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653035&cp=746f7073657269616c792e736b&
20:43:03 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653036&cp=746f7073657269616c792e736b&
20:43:03 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653036&cp=746f7073657269616c792e736b&
20:43:03 T:5556 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653038&cp=746f7073657269616c792e736b&
20:43:03 T:5556   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653038&cp=746f7073657269616c792e736b&
20:43:03 T:7944 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653037&cp=746f7073657269616c792e736b&
20:43:03 T:7944   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653037&cp=746f7073657269616c792e736b&
20:43:06 T:7128  NOTICE: ["Initializing provider topserialy.sk with settings {'downloads': '', 'quality': '0'}"]
20:43:06 T:7128  NOTICE: [u'Found resolvable b3BlbmxvYWRmdWNrZG1jYXRyb2xscw==/mWS7ywyd_q4/']
20:43:06 T:7128  NOTICE: [u'Found resolvable http://www.flashx.tv/embed-6i32psssfpin-720x405.html']
20:43:06 T:7128  NOTICE: [u'Found resolvable //www.zumail.cz/tracker/i8eAfjhE3eWo8ne/']
20:43:06 T:7128  NOTICE: [u'Resolving b3BlbmxvYWRmdWNrZG1jYXRyb2xscw==/mWS7ywyd_q4/']
20:43:06 T:7128  NOTICE: [u'No resolver found for b3BlbmxvYWRmdWNrZG1jYXRyb2xscw==/mWS7ywyd_q4/']
20:43:06 T:7128  NOTICE: [u'Resolving http://www.flashx.tv/embed-6i32psssfpin-720x405.html']
20:43:06 T:7128  NOTICE: ["Using resolver 'flashx'"]
20:43:07 T:7128  NOTICE: [u'There was an error resolving http://www.flashx.tv/embed-6i32psssfpin-720x405.html']
20:43:07 T:7128  NOTICE: [u'Resolving //www.zumail.cz/tracker/i8eAfjhE3eWo8ne/']
20:43:07 T:7128  NOTICE: [u'No resolver found for //www.zumail.cz/tracker/i8eAfjhE3eWo8ne/']
20:43:09 T:7096   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653031&cp=746f7073657269616c792e736b&]
20:43:09 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653031&cp=746f7073657269616c792e736b&
20:43:09 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653031&cp=746f7073657269616c792e736b&
20:43:09 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653038&cp=746f7073657269616c792e736b&
20:43:09 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653038&cp=746f7073657269616c792e736b&
20:43:09 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653037&cp=746f7073657269616c792e736b&
20:43:09 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653037&cp=746f7073657269616c792e736b&
20:43:09 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653036&cp=746f7073657269616c792e736b&
20:43:09 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653036&cp=746f7073657269616c792e736b&
20:43:09 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653035&cp=746f7073657269616c792e736b&
20:43:09 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653035&cp=746f7073657269616c792e736b&
20:43:09 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653034&cp=746f7073657269616c792e736b&
20:43:09 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653034&cp=746f7073657269616c792e736b&
20:43:09 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653033&cp=746f7073657269616c792e736b&
20:43:09 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653033&cp=746f7073657269616c792e736b&
20:43:09 T:1824 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653032&cp=746f7073657269616c792e736b&
20:43:09 T:1824   ERROR: InputStream: Error opening, plugin://plugin.video.topserialy.sk/?play=687474703a2f2f7777772e746f7073657269616c792e736b2f73657269616c792f7468652d6e696768742d6f662d733031653032&cp=746f7073657269616c792e736b&
20:43:15 T:7096  NOTICE: Storing total System Uptim

**Comment by jose1711** [comment]
bohuzial, toto sa bude objavovat az do doby, kedy sa nam nepodari nejak vyriesit problem s aktualizaciami resolverov. momentalne na to vsak nemam cas

**Comment by co5mo** [comment]
asi som to uz pisal ale mozno by sa dal implementovat urlresolver na youwatch a podobne a nebolo by treba riesit update resolverov bolo by fajn mat aj sk dabind dakujem

**Comment by jose1711** [comment]
skus najnovsi update (po instalacii urlresolvera)

**Comment by co5mo** [comment]
skvele dakujem ide to
tu napr https://www.topserialy.to/serialy/the-big-bang-theory-s01e02
nasiel 2 zdroje flashx (sk) a openload (cz) ale nie youwatch (sk)

**Comment by jose1711** [comment]
youwatch pridany v e252cb71
