### ISSUE TITLE
Nefunkčný plugin Topserialy.sk

### ISSUE THREAD

**Issue by OrbisPictus** [jose1711/plugin.video.topserialy.sk#3]
Ahojte,
plugin topserialy.sk je pre mňa novinka, ale keď som ho chcel rozbehať, tak mi nejde spustiť ani jeden seriál. Je to funkčné, alebo je to problém len u mňa?
Pri spustení hocijakého seriálu mi vypíše: "Nebyl nalezen zadny video embed. Zkontrolujte stranku, pripadne nahlaste chybu pluginu." 
Pripájam aj log. Ďakujem za odpoveď.
[kodi.txt](https://github.com/jose1711/plugin.video.topserialy.sk/files/737116/kodi.txt)

**Comment by jose1711** [comment]
zdravim,

len velmi skaredy v commite f45d09637a6bed0b065dffd624918493aa7514c4. problemom vsak stale ostava velke mnozstvo rozbitych resolverov (napr. casto sa vyskytujuci openload).

**Comment by OrbisPictus** [comment]
Ďakujem. Skúšal som, ale ešte sa mi nepodarilo nájsť taký seriál, ktorý by spustilo :) Teraz stále už len vypisuje "Nelze získat video link...." To bude asi tými resolvermi, však? No nič, vyzeralo to zaujímavo, ale asi to bude nepoužiteľné, nakoľko nájsť tam niečo funkčné bude asi rarita :) Ešte raz vďaka.

**Comment by jose1711** [comment]
pogugluj a nainstaluj si do kodi URLResolver plugin, potom si nahod najnovsiu (dnesnu) verziu topserialy.sk a vyskusaj znova.

**Comment by OrbisPictus** [comment]
OK. URLresolver mám vo verzii 3.0.27. topserialy vo verzii 0.0.2. Pri prvom videu to po mne chcelo, aby som si spároval IP adresu cez openload.co. Podľa stránky je to spárované správne, ale keď pustím nejaké video, tak mi vyhodí chybu. Iba hlášku navrchu, ktorá zmizne. Pripájam log. Ale vyzerá to tak, že to okrem mňa asi nikto nepoužíva, tak neviem, či sa oplatí kvôli jednému človeku toľko mrhať energiou :) každopádne vďaka za ochotu. Zatiaľ som to skúšal len na WIN. Zajtra vyskúšam aj na androide, či to tam náhodou nepôjde.
[kodi.txt](https://github.com/jose1711/plugin.video.topserialy.sk/files/737899/kodi.txt)

**Comment by jose1711** [comment]
so mnou uz su to dvaja ludia :-) aktualne su povolene len 2 zdroje - openload a flashx, preto nefunguje to, co predtym slo. vyskusaj prosim verziu 0.0.3 a napis, ci sa nieco zmenilo.

**Comment by OrbisPictus** [comment]
Ahoj, takže teraz večer som zapol KODI a plugin sa sám aktualizoval :) a okrem jediného seriálu išlo všetko, čo som skúšal. Jediné "problémy", ktoré som zaznamenal je, že pri výbere kvality mi všade napísalo "openload en(???)" a keď som to pustil, tak to išlo aj v cz aj v sk jazyku. Ale to je jedno, hlavne, že to ide :) ale ešte sa opýtam, je to aj moja prvá skúsenosť s openload a keď som to skúšal, tak asi po každom 4 seriáli som to musel párovať znova. Nedá sa to nastaviť nejako natrvalo?

**Comment by jose1711** [comment]
to en/cz/sk by mal byt jazyk detegovanych titulkov. podrobnosti o parovani (preco, zaco, naco) su tu http://koditips.com/kodi-openload-pair-pairing-details-help/. pise sa, ze to parovanie by malo platit 4 hodiny, no vyzera, ze sa spocitava cas trvania jednotlivych resolvovanych odkazov. funguje aj flashx resolver?

**Comment by OrbisPictus** [comment]
tak to netuším. ale išlo mi všetko okrem jedného seriálu. Agent Carter. Ale tam ani neotvorí zoznam častí v 1. sérii. flashx netuším či ide. Ani pri jedno seriály mi to nevyhodilo nejakú ponuku, kde by bolo spomenuté flashx. V logu je všade písané napr. toto: "18:57:30 T:10732   ERROR: URLResolver: ResolverError Error - From: flashx Link: https://www.flashx.tv/embed.php?c=sojl108dk5sc: No Video Link Found" takže vyzerá to tak, že flashx nejde, ale seriál mi otvorí cez openload. Obrázok je konkrétne pre 12 opíc, tak isto ako výpis z logu ku flashx.
![image](https://cloud.githubusercontent.com/assets/25182804/22436763/ba05873c-e725-11e6-82cf-5d71036eca07.png)

**Comment by uniqit01** [comment]
Caute, tak uz sme minimalne traja :)  Ja som vo svete Kodi novy, a len vcera som objavil tento addon, a kedze web dobre poznam potesil som sa ze sa niekto podujal urobit aj addon. Pred chvilou som si ho updatol na verziu 0.0.3 a co som skusil par serialov isli vsetky (po sparovani openload). Takze zamna zatial velka pochvala a super praca, dufam ze tento addon bude fungovat este dlho :)

**Comment by jose1711** [comment]
zaujimave, flashx mi slape v pohode. mozno mam stastie. agent carter prva seria by uz mohla fungovat (0.0.4)

**Comment by OrbisPictus** [comment]
wau. to je teda promptné riešenie :) už to ide. skúšal som aj vymazať urlresolver a nainštalovať nanovo. pritom vypísalo aj to, že urobilo update na flashx, ale aj tak je to stále rovnaké, teda asi nefunkčné :D pre info pripájam log, určite z neho vyčítaš viac ako ja :) mne to veľa nehovorí, len samá chybová hláška pri otvorení videa.
[kodi.txt](https://github.com/jose1711/plugin.video.topserialy.sk/files/740330/kodi.txt)

**Comment by uniqit01** [comment]
Ja som si vsimol, ze mi nefunguje vyhladavanie. Dam vyhladat nejaky serial, najde ho, ale ked kliknem na jeho meno, vyhodi mi to len Error okienko a v nom hlasku: please check error log. Aj by som ho pozrel ale neviem kde ho najst, Kodi mi bezi cez LibreElec na RPI3, a nic ine nanom nemam tak ani neviem ako by som   ho sem postol.

**Comment by pstruh** [comment]
cez prikazovy riadok pusti:  pastebinit /storage/.kodi/temp/kodi.log
a pastni url co ti vyhodi

**Comment by co5mo** [comment]
hello skusa to tu niekto na kodi 16? mam pocit ze tam nevyskakuje okno s vyberom streamu... mozno by bolo fajn pridat autoselekciu jazyku namiesto kvality
dakujem

**Comment by jose1711** [comment]
@co5mo ja to testujem na kodi 16

**Comment by OrbisPictus** [comment]
Ja to mám tiež na kodi 16.1. A mám to Win aj na Androide. Na oboch mi to ponúka kvalitu na výber.  Viď pár postov vyššie .

**Comment by co5mo** [comment]
ok dakujem

**Comment by uniqit01** [comment]
Caute, takze tu je moj log, ktory obsahuje chybu ked sa snazim dostat do vyhladaneho serialu(opisanu vyssie): http://sprunge.us/VbCj

A mne to taktiez neponuka na vyber zdroj videa, po kliknuti na epizodu sa mi rovno spusti stream. Kodi 16.1 mi bez cez LibreElec 7.0.3 na RPI3. Vyskusane na 5-6 serialoch. Vacsinou stale spusta openload.

**Comment by jose1711** [comment]
prosim pre nesuvisiace problemy zalozte novy issue. dik

**Comment by uniqit01** [comment]
Ponuka na vyber zdroja sa mi nezobrazuje, rovno sa mi spusti stream. Kodi 16.1 (LibreElec 7.0.3).

**Comment by OrbisPictus** [comment]
Ja som toho najnovšieho Sherlocka teraz vyskúšal a mne ukáže na výber 4 streamy. Tak isto ako na tom screene vyššie. Nemáte tam predvolenú nejakú kvalitu streamu? Ja mám nastavené "spýtať sa" a spýta sa :D

**Comment by uniqit01** [comment]
Aha jasne, ja som to mal nastavene na najlepsiu kvalitu. Ok super uz to ide, a funguje uz aj vyhladavanie (v0.0.6). Super diky, good job.

**Comment by jose1711** [comment]
kedze vacsina veci funguje, zavieram
